version: '3.4'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5431:5432

  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5050:5050
    links:
      - "db:pgsql-server"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    image: backend
    # ports:
    #   - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./workbench_web/backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  frontend:
    image: frontend
    depends_on:
      - backend
    ports:
      # Expose the nginx server running on container's port 80 to the host's port 80
      # Note that in the past you have been using "vue-cli-service serve" which uses port 8080 by default
      - 80:80
    build:
      context: ./workbench_web/frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}


volumes:
  app-db-data:
  pgadmin-data:

# networks:
#   backbone:
#     driver: bridge