version: '3.4'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5431:5432

  backend:
    image: backend
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: ./workbench_web/backend
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5050:5050
    links:
      - "db:pgsql-server"
    volumes:
      - pgadmin-data:/var/lib/pgadmin



volumes:
  app-db-data:
  pgadmin-data:
